Use the LTSS base containers for LTSS builds
SUSE/BCI-dockerfile-generator pull request #1054
Opened 2024-04-30 12:55 UTC by dirkmueller

This also fixes the default base container to bci-base rather than sle15

2024-04-30 13:11 UTC, dcermak requested changes
Breaks the tests and causes a giant churn of all dockerfiles

2024-04-30 14:53 UTC, dirkmueller commented
> Breaks the tests and causes a giant churn of all dockerfiles

so is the "requests changes" on "giant churn of all dockerfiles" or "breaks the tests" ? it's not clear to me what I can do to get a review from you?

2024-05-02 15:50 UTC, dirkmueller commented
iirc changes should go in together with #1069

2024-05-03 11:27 UTC, dirkmueller commented
In the hope that the LTSS base fix can go in, I've reverted the bci-base change for now.

2024-05-05 11:57 UTC, dcermak commented
> iirc changes should go in together with #1069

That's an automated PR that updated the prjconf

2024-05-05 11:57 UTC, dcermak approved these changes

2024-05-05 11:57 UTC, merged