Use multistage build to remove zypper stack from final image
SUSE/BCI-dockerfile-generator pull request #1387
Opened 2024-07-10 11:31 UTC by dirkmueller

This can be used for other app containers as well. Unsure if it should be done globally for all application containers.

2024-07-11 12:13 UTC, dcermak requested changes
Sorry, but I don't like this. We have a much better way to create small containers: use kiwi instead of resorting to this multistage hackery.

2024-07-11 12:27 UTC, dirkmueller commented
"requests changes" means what needs to be changed? we can't change to kiwi build easily because it changes repositories so qa pipelines etc needs adjustment. 

I don't think kiwi is a better approach. enabling a multistage build is seamless and allows to remove packages that frequently attract vulnerabilities.

2024-07-17 07:38 UTC, dcermak commented
> "requests changes" means what needs to be changed? we can't change to kiwi build easily because it changes repositories so qa pipelines etc needs adjustment.

I wouldn't find the change that intrusive, given that this just touches tomcat, that hasn't been setup yet.

> I don't think kiwi is a better approach. enabling a multistage build is seamless and allows to remove packages that frequently attract vulnerabilities.

Kiwi allows us to do the same. One disadvantage of the multistage build is, that the `.packages` file that OBS produces is no longer correct. E.g. [`suse-tomcat-10-15.6.10.x86_64-35.7.packages`](https://build.opensuse.org/build/home:defolos:BCI:Staging:SLE-15-SP6:6-1387/containerfile/x86_64/tomcat-10-image/suse-tomcat-10-15.6.10.x86_64-35.7.packages) contains zypper and all its dependencies. The SBOMs appear to be correct though.

2024-07-17 07:49 UTC, dcermak commented
> > I don't think kiwi is a better approach. enabling a multistage build is seamless and allows to remove packages that frequently attract vulnerabilities.
> 
> Kiwi allows us to do the same. One disadvantage of the multistage build is, that the `.packages` file that OBS produces is no longer correct. E.g. [`suse-tomcat-10-15.6.10.x86_64-35.7.packages`](https://build.opensuse.org/build/home:defolos:BCI:Staging:SLE-15-SP6:6-1387/containerfile/x86_64/tomcat-10-image/suse-tomcat-10-15.6.10.x86_64-35.7.packages) contains zypper and all its dependencies. The SBOMs appear to be correct though.

The `report` files suffer from the same flaw as the `packages` files, e.g. [`suse-tomcat-10-15.6.10.x86_64-35.7.report`](https://build.opensuse.org/build/home:defolos:BCI:Staging:SLE-15-SP6:6-1387/containerfile/x86_64/tomcat-10-image/suse-tomcat-10-15.6.10.x86_64-35.7.report) contains the whole zypper stack too. This will mess up the reports that @msmeissn generates.

2024-08-08 18:59 UTC, dirkmueller commented
> The `report` files suffer from the same flaw as the `packages` files, e.g. [`suse-tomcat-10-15.6.10.x86_64-35.7.report`](https://build.opensuse.org/build/home:defolos:BCI:Staging:SLE-15-SP6:6-1387/containerfile/x86_64/tomcat-10-image/suse-tomcat-10-15.6.10.x86_64-35.7.report) contains the whole zypper stack too. This will mess up the reports that @msmeissn generates.

Marcus mentioned to me that it would not be an issue for him to switch to SBOMs for reports, which I think would make most sense.

2024-08-13 14:32 UTC, dcermak requested changes
I'm not a giant fan of another mass change but I don't know a better way either. My two complaints are:
- the README is now wrong as it suggests to use zypper in two places
- lack of `curl` in the tomcat container

2024-08-14 11:33 UTC, dirkmueller commented on src/bci_build/templates.py
> +COPY --from=target / /target
yes. see https://opensource.suse.com/bci-docs/guides/use-with-golang/

2024-08-14 11:39 UTC, dirkmueller commented on src/bci_build/package/apache_tomcat.py
> +            "sed",
merged

2024-08-14 12:10 UTC, dcermak approved these changes

2024-08-14 12:15 UTC, merged