remove %RELEASE% suffixed tags for the additional_versions
SUSE/BCI-dockerfile-generator pull request #1670
Opened 2024-09-13 15:35 UTC by dirkmueller

This partially reverts cb350c0b2f9efbb7694ed00f2cbf913fa49a88ca which didn't really have a description on why it was done. Removing them is a requisite for appcol listing.

2024-09-16 08:20 UTC, dcermak requested changes
I'm not opposed to not appending `%RELEASE%`, but atm it leads to rather useless tags:
```diff
#!BuildTag: bci/kiwi:10
#!BuildTag: bci/kiwi:10-%RELEASE%
#!BuildTag: bci/kiwi:10.1
-#!BuildTag: bci/kiwi:10.1-%RELEASE%
#!BuildTag: bci/kiwi:10.1.8
-#!BuildTag: bci/kiwi:10.1.8-%RELEASE%
```
IMHO, it really only makes sense to have `bci/kiwi:10.1.8-%RELEASE%`, all the other tags have a very limited usefulness. If we have to get rid of this "shoot the fly with the cannon approach", then I'd go all in and just drop the `-%RELEASE%` suffix entirely.

2024-09-16 08:53 UTC, dirkmueller commented
> I'm not opposed to not appending `%RELEASE%`, but atm it leads to rather useless tags:
> 
> ```diff
> #!BuildTag: bci/kiwi:10
> #!BuildTag: bci/kiwi:10-%RELEASE%
> #!BuildTag: bci/kiwi:10.1
> -#!BuildTag: bci/kiwi:10.1-%RELEASE%
> #!BuildTag: bci/kiwi:10.1.8
> -#!BuildTag: bci/kiwi:10.1.8-%RELEASE%
> ```
> 
> IMHO, it really only makes sense to have `bci/kiwi:10.1.8-%RELEASE%`, all the other tags have a very limited usefulness. If we have to get rid of this "shoot the fly with the cannon approach", then I'd go all in and just drop the `-%RELEASE%` suffix entirely.

this is because "version" is not set correctly (it should be the full version). the tags will get better with the other PRs related to this getting merged.

2024-09-17 07:23 UTC, dcermak approved these changes

2024-09-24 09:24 UTC, alexandrevicenzi approved these changes

2024-09-24 16:17 UTC, dirkmueller commented
(this still needs a better determination what is the most "fixed" tag to attach a -%RELEASE suffix to)

2024-09-24 19:50 UTC, merged