Use ~postgres/data as PG_DATA
SUSE/BCI-dockerfile-generator pull request #296
Opened 2023-03-15 21:46 UTC by dirkmueller

the SUSE SLE packages are expecting to run postgresql below the postgres user home, and locating the data dir inside makes the docker entrypoint set permissions on the volume on first start.

2023-03-16 06:59 UTC, dirkmueller commented
wow this container is broken :/ the "su" hack is not correct.

2023-03-16 07:18 UTC, dcermak commented
> the SUSE SLE packages are expecting to run postgresql below the postgres user home, and locating the data dir inside makes the docker entrypoint set permissions on the volume on first start.

Interesting, the previous iteration worked as well :thinking: though.

2023-03-16 12:29 UTC, dcermak requested changes
This submission breaks multiple use cases:
- running the container as `--user postgres` is now broken
- running with a different PGDATA location is broken

2023-03-16 14:05 UTC, dirkmueller commented
> * running the container as `--user postgres` is now broken

it appears this is an ordering issue. `-v something:/somewhere --user postgres` fails while `--user postgres -v something:/somewhere` is working. the --user setting has influence on how the volume mountpoint directory is created. 

> * running with a different PGDATA location is broken

fixed.

2023-03-21 07:50 UTC, dcermak requested changes
The unit tests are now broken

2023-03-30 12:32 UTC, merged