Add openqa-single-instance container
SUSE/BCI-dockerfile-generator pull request #566
Opened 2023-08-01 15:38 UTC by dcermak

2023-08-01 16:18 UTC, okurz reviewed
The change looks ok but is heavily duplicating the upstream container Dockerfile so sooner or later this will also fail on changes. With that I suggest to not merge that until we can come up with a way with less duplications

2023-08-01 20:43 UTC, dcermak commented
> The change looks ok but is heavily duplicating the upstream container Dockerfile so sooner or later this will also fail on changes. With that I suggest to not merge that until we can come up with a way with less duplications

@okurz I think you misunderstood my suggestion of this, my idea was to remove the need for you to maintain the `Dockerfile` and instead use the BCI tooling. Hence this is not duplication, but a replacement.

2023-08-01 20:48 UTC, okurz commented
Well, that makes more sense but isn't it a good idea to have a Dockerfile in the upstream repo usable by anyone?

2023-08-02 07:53 UTC, dcermak commented
> Well, that makes more sense but isn't it a good idea to have a Dockerfile in the upstream repo usable by anyone?

Well that really depends on your expectations as a project. Given that your Dockerfile only works on OBS anyway, I wouldn't see that much of a need. But that is your call to make.

2023-08-02 07:55 UTC, dirkmueller commented on src/bci_build/package.py
> +    custom_description="A complete openQA instance composed of all necessary components to execute openQA tests including an openQA worker",
this is missing at least `{based_on_container}` at the end

2023-08-02 07:56 UTC, dirkmueller commented on src/bci_build/package.py
> +    custom_end="HEALTHCHECK CMD curl -f http://localhost || exit 1",
theoretically the `|| exit 1` seems redundant here. and maybe use curl -sf ?

2023-10-12 11:50 UTC, dirkmueller requested changes
needs rebase. do we still go forward with this approach at all?

2023-10-12 11:53 UTC, dcermak commented
Unless @okurz would like this container, I'd just close this. No need to provide a container competing with openQA upstream.

2023-10-12 12:29 UTC, okurz commented
Agreed. So far we are good with the openQA upstream container definition

2023-10-12 12:35 UTC, closed without merging