Use Path() where possible to cleanup the code a little
SUSE/BCI-dockerfile-generator pull request #885
Opened 2024-01-30 21:01 UTC by dirkmueller

2024-01-31 08:36 UTC, dcermak commented
Thanks, this LGTM! Please just run `poetry run ruff check --fix` to sort the imports.

2024-01-31 22:02 UTC, dcermak requested changes
`read_bytes` is messing with the pcp readme, I think we should be using `read_text` instead

2024-01-31 22:02 UTC, dcermak commented on src/bci_build/package/appcontainers.py
> +_RMT_ENTRYPOINT = (Path(__file__).parent / "rmt" / "entrypoint.sh").read_bytes()
```suggestion
_RMT_ENTRYPOINT = (Path(__file__).parent / "rmt" / "entrypoint.sh").read_text()
```

2024-01-31 22:02 UTC, dcermak commented on src/bci_build/package/appcontainers.py
> +_POSTGRES_LICENSE = (Path(__file__).parent / "postgres" / "LICENSE").read_bytes()
```suggestion
_POSTGRES_ENTRYPOINT = (
    Path(__file__).parent / "postgres" / "entrypoint.sh"
).read_text()
_POSTGRES_LICENSE = (Path(__file__).parent / "postgres" / "LICENSE").read_text()
```

2024-01-31 22:02 UTC, dcermak commented on src/bci_build/package/appcontainers.py
> +    ).read_bytes()
```suggestion
    ).read_text()
```

2024-01-31 22:02 UTC, dcermak commented on src/bci_build/package/appcontainers.py
> +    _NGINX_FILES[filename] = (Path(__file__).parent / "nginx" / filename).read_bytes()
```suggestion
    _NGINX_FILES[filename] = (Path(__file__).parent / "nginx" / filename).read_text()
```

2024-01-31 22:02 UTC, dcermak commented on src/bci_build/package/basecontainers.py
> +OSC_CHECKOUT = (Path(__file__).parent / "gitea-runner" / "osc_checkout").read_bytes()
```suggestion
OSC_CHECKOUT = (Path(__file__).parent / "gitea-runner" / "osc_checkout").read_text()
```

2024-01-31 22:12 UTC, dirkmueller commented
well, that makes it a str rather than bytes, which is what the functions are supposed to be handling. even though I changed it everywhere, there's something special about the PCP README..

2024-01-31 22:40 UTC, dcermak commented
I guess this is the culprit: https://github.com/SUSE/BCI-dockerfile-generator/blob/1e8a4900b58cb89410297dc7a9d15b6d78488519/src/bci_build/package/__init__.py#L1007

2024-02-01 10:21 UTC, dcermak commented on src/bci_build/package/__init__.py
> +                return self.extra_files["README.md"].decode('utf-8')
```suggestion
                return self.extra_files["README.md"].decode("utf-8")
```

2024-02-01 13:31 UTC, merged

2024-02-01 13:31 UTC, dcermak commented
Thank you!