replace BASALT mentions by SLCI
SUSE/BCI-dockerfile-generator pull request #949
Opened 2024-03-08 07:40 UTC by Priyankasaggu11929

copy of https://github.com/SUSE/BCI-dockerfile-generator/pull/948

2024-03-08 09:17 UTC, Priyankasaggu11929 commented
Thanks Dan. :smile: 

Created an empty SLCI branch, and updated the gh workflows.

One of [the CI job](https://github.com/SUSE/BCI-dockerfile-generator/actions/runs/8201108249/job/22429187145?pr=949#step:11:148) is failing due to missing "SLCI" obs sub-project

```
 DEBUG: running command osc --config=/tmp/tmpqe_3ob4s meta prj --file=/tmp/tmphr2zqasa home:defolos:BCI:Staging:SLCI:SLCI-PgWkG
DEBUG: command terminated with 1, stdout: Sending meta data...
, stderr: Server returned an error: HTTP Error 400: Bad Request
project validation error: 1:0: ERROR: Expecting element project, got status
```

2024-03-08 09:24 UTC, dcermak commented
Yes, the issue is that devel:BCI:SLCI does not exist on OBS (yet). But I'd wait with creating it, as we do not have the final name for SLCI (yet…)

2024-03-11 07:26 UTC, dirkmueller requested changes
It was renamed to SLCC (or SLCS?)

2024-03-11 07:45 UTC, dcermak commented
> It was renamed to SLCC (or SLCS?)

The name is not fixed yet. The purpose of this PR is mostly to find out what breaks and what needs adjustment.

2024-04-25 14:09 UTC, Priyankasaggu11929 commented
@dcermak, just confirming this change is still needed right? 

I'll send a PR to change it to SLCC then.

2024-04-25 14:28 UTC, dcermak commented
Priyanka Saggu ***@***.***> writes:

> @dcermak, just confirming this change is still needed right? 
>
> I'll send a PR to change it to SLCC then.

Yes, this change is still needed, but please don't modify the PR
anymore. I have made extensive changes and will have to do more to get
the new setup to work.

2024-04-26 04:51 UTC, Priyankasaggu11929 commented
> Yes, this change is still needed, but please don't modify the PR
anymore. I have made extensive changes and will have to do more to get
the new setup to work.

Ack.

2024-05-03 14:35 UTC, dcermak commented on src/bci_build/package/appcontainers.py
> +    for os_version in ALL_BASE_OS_VERSIONS
good catch, should be fixed now

2024-05-07 09:09 UTC, dirkmueller commented on src/bci_build/package/__init__.py
> +            return "16.0.0"
16.0 here as well to be consistent.

2024-05-07 09:10 UTC, dirkmueller commented
this is getting pretty large to review. is there any way to split this up a little? for example the introduction of SLCC version identifiers and the merge of ImageProperties back could be separated from the rest. also the staging bot project setup could be separate.

2024-05-07 09:11 UTC, dirkmueller commented
sorry, fatfingered.

2024-05-07 15:39 UTC, dirkmueller commented on src/staging/bot.py
> +from typing import Coroutine
why? https://docs.python.org/3/library/typing.html#typing.Coroutine and https://peps.python.org/pep-0585/

2024-06-21 08:38 UTC, dirkmueller commented on src/bci_build/package/slcc_base.py
> +zypper -n ar --gpgcheck --enable 'https://updates.suse.com/SUSE/Products/ALP-Dolomite/1.0/$basearch/product/' repo-slci
`repo-slcc`

2024-06-21 08:49 UTC, dirkmueller commented
can you please split this into chunks? this is not easily reviewable as a couple of completely unrelated things are lumped together. 

all the refactorings could be separate and go in already..

2024-08-03 12:41 UTC, dirkmueller commented on src/bci_build/package/appcontainers.py
> +    for os_version in ALL_BASE_OS_VERSIONS
this seems wrong for appcontainers

2024-08-03 12:44 UTC, dirkmueller commented on src/bci_build/package/__init__.py
> +                f"{self._registry_prefix}/{prefix}{name}:%OS_VERSION_ID_SP%",
why are we removing the bci- prefix from the container names here?

2024-08-03 13:12 UTC, dirkmueller requested changes

2024-08-03 13:12 UTC, dirkmueller commented on src/staging/bot.py
> +class TripleZeroPackageGroups:
can we split all those TripleZero packages groups commits to the bot into a separate PR? it's messy enough as is to review this and it seems entirely orthogonal to SLCC enablement.

2024-08-03 13:12 UTC, dirkmueller commented on src/staging/project_setup.py
> +META_TEMPLATE = jinja2.Template("""<project name="{{ project_name }}">
same project_setup could be an entirely separate PR

2025-03-24 15:38 UTC, dirkmueller commented
splitted remaining SLFO/BASALT/SLCC work into https://github.com/SUSE/BCI-dockerfile-generator/pull/2366. closing this one.

2025-03-24 15:38 UTC, closed without merging