Add rendering READMEs from a jinja template stored in git
SUSE/BCI-dockerfile-generator pull request #961
Opened 2024-03-19 12:57 UTC by dirkmueller

If README.md is not already injected via extra_files, the generator now looks for a README.md.j2 in the package directory and renders it instead.

2024-03-19 16:06 UTC, dcermak requested changes

2024-03-19 16:06 UTC, dcermak commented on src/bci_build/package/registry/README.md.j2
> +```
```suggestion
```yaml
---
version: 0.1
log:
  level: info
storage:
  filesystem:
    rootdirectory: /var/lib/docker-registry
http:
  addr: 0.0.0.0:5000
```
```

2024-03-19 16:06 UTC, dcermak commented on src/bci_build/package/registry/README.md.j2
> +    mkdir -p /var/lib/docker-registry
```suggestion
mkdir -p /var/lib/docker-registry
```

2024-03-19 16:06 UTC, dcermak commented on src/bci_build/package/registry/README.md.j2
> +        -v /var/lib/docker-registry:/var/lib/docker-registry --name registry {{ image.reference }}
```suggestion
podman run -d --restart=always -p 5000:5000 -v /path/to/config.yml:/etc/docker/registry/config.yml \
    -v /var/lib/docker-registry:/var/lib/docker-registry --name registry {{ image.reference }}
```

2024-03-19 16:06 UTC, dcermak commented on src/bci_build/package/registry/README.md.j2
> +sudo podman generate system registry > /etc/systemd/system/registry.service
```suggestion
sudo podman generate systemd registry > /etc/systemd/system/registry.service
```

2024-03-19 16:06 UTC, dcermak commented on src/bci_build/package/registry/README.md.j2
> +# License
```suggestion
## License
```

2024-03-19 21:10 UTC, dcermak commented
@dmpop can you please take a look at the Readmes?

2024-03-22 08:54 UTC, dmpop submitted a review, later dismissed
Just a few minor tweaks to make the style more README-like,

2024-03-22 08:54 UTC, dmpop commented on src/bci_build/package/busybox/README.md.j2
> +uses GNU Coreutils may require modification to work with BusyBox.
```suggestion
The SLE BCI-BusyBox image comes with the most basic tools provided by the BusyBox project. The image contains no GPLv3 licensed software. When using the image, keep in mind that there are differences between the BusyBox tools and the GNU Coreutils. This means that scripts written for a system that uses GNU Coreutils may require modification to work with BusyBox.
```

2024-03-22 08:54 UTC, dmpop commented on src/bci_build/package/busybox/README.md.j2
> +# SLE BCI-BusyBox: When you need the smallest and GPLv3-free image
```suggestion
# SLE BCI-BusyBox: the smallest and GPLv3-free image
```

2024-03-22 08:54 UTC, dmpop commented on src/bci_build/package/micro/README.md.j2
> +# SLE BCI-Micro: When you need to deploy static binaries
```suggestion
# SLE BCI-Micro: Suitable for deploying static binaries
```

2024-03-22 08:54 UTC, dmpop commented on src/bci_build/package/minimal/README.md.j2
> +# SLE BCI-Minimal: When you do not need Zypper
```suggestion
# SLE BCI-Minimal: Container image without Zypper
```

2024-03-22 08:54 UTC, dmpop commented on src/bci_build/package/minimal/README.md.j2
> +prone to errors.
```suggestion
SLE BCI-Minimal comes without Zypper, but it does have the RPM package manager installed. While RPM can install and remove packages, it lacks support for repositories and automated dependency resolution. The SLE BCI-Minimal image is therefore intended for creating deployment containers, and then installing the desired RPM packages inside the containers. While you can install the required dependencies, you need to download and resolve them manually. However, this approach is not recommended as it is prone to errors.
```

2024-03-22 08:54 UTC, dmpop commented on src/bci_build/package/registry/README.md.j2
> +
```suggestion
You can also create an empty directory for storing the images outside the container:

```

2024-03-22 08:54 UTC, dmpop commented on src/bci_build/package/registry/README.md.j2
> +you can create a systemd service:
```suggestion
The registry is available at `http://localhost:5000`. To keep the registry running after a reboot, create a systemd service as follows:
```

2024-03-22 17:06 UTC, merged